config/routes.rb
Rails.application.routes.draw do
  resources :employees
  devise_for :admins

  root "pages#home"
  get "admin", to: "pages#admin_panel", as: "admin_panel"
  get "about", to: "pages#about", as: "about"

  resources :items
  get "search", to: "items#search"

  get  "items/:id/update", to: "entries#new", as: "new_entry"
  post "items/:id/update", to: "entries#create"
  get  "update", to: "entries#index", as: "entries"
  post "update", to: "entries#update", as: "update_entries"

  get  "items/:id/waste", to: "wastes#new", as: "new_waste"
  post "items/:id/waste", to: "wastes#create"
  get  "waste", to: "wastes#index", as: "wastes"
end

app/views/pages/about.html.slim
= provide :title, "About"

section.hero.is-info
  .hero-body
    .container


.columns
  .column
  .column.box
    .level
      .level-item
        = image_tag "logo.png"
    p CookieCounter tracks what"s in-stock and on-order throughout the entirety of your inventory.
    br
    p It"s mobile-friendly and available on any device with a web browser.
    br
    p Find the code on #{link_to "Github!", "https://github.com/brxck/cookie-counter"}
  .column

section.section
  .level
    .level-item
      .subtitle.is-5 Developed by Brock McElroy
  .level
    .level-item
      .buttons.has-addons
        a.button.is-large href="http://brockmcelroy.com"
          span = fa_icon "compass"
        a.button.is-large href="mailto:brxck@protonmail.com"
          span = fa_icon "send-o"
        a.button.is-large href="https://github.com/brxck"
          span = fa_icon "github"
    .level
      .level-item

app/views/pages/admin_panel.html.slim
= provide :title, "Admin Panel"

.columns
  .column
    .box
      .level
        label.label Employees
        .buttons.has-addons
          = link_to "Manage", employees_path, class: "button"
          = link_to "New", new_employee_path, class: "button"

      .level
        label.label Items
        .buttons.has-addons
          = link_to "Manage", items_path, class: "button"
          = link_to "New", new_item_path, class: "button"

      .level
        label.label Admin
        .buttons.has-addons
          = link_to "Manage", edit_admin_password_path, class: "button"
  .column

app/views/pages/home.html.slim
= provide :title, "Home"

section.level
  .level-item
    h1.title.is-4 #{fa_icon "dashboard"} Dashboard

.columns
  .column
    article.box
      .level.is-mobile
        .level-left
          .level-item
            p.subtitle.is-5 #{fa_icon "pencil"} Inventory
        .level-right
          .level-item
            .buttons.has-addons
                = link_to "View", items_path(anchor: "main"), class: "button"
                = link_to "Update", entries_path(anchor: "main"), class: "button is-info"
            
      
      div
        p #{@entries_updated} of #{Item.count} items updated in the last week.
        br
        progress.progress.is-info #{@percent_updated}%
      
      br

      div
        p Updated #{time_ago_in_words @last_update} ago
        p by #{@last_update_user}

    article.box
      .level.is-mobile
        .level-left
          .level-item
            p.subtitle.is-5 #{fa_icon "exclamation-circle"} Low Stock
        .level-right
          .level-item
            = link_to "View", "#", class: "button is-success"    
    
      - if @low_stock.any?
        table.table.is-fullwidth       
          tbody
            - @low_stock.each do |item|
              tr
                td = link_to item.name, item_path(anchor: "main", id: item.id)
                td = item.in_stock
      - else
        p No low stock.

  .column
    article.box      
      .level.is-mobile
        .level-left
          .level-item
            p.subtitle.is-5 #{fa_icon "trash"} Today's Waste
        .level-right
          .level-item
            .buttons.has-addons
              = link_to "View", wastes_path(anchor: "main"), class: "button" 
              = link_to "Log", new_waste_path(anchor: "main", id: 1), class: "button is-danger"
    
      .level
        - if @waste.any?
          table.table.is-fullwidth
            - @waste.each do |entry|
              tr
                td = link_to entry.item.name, item_path(anchor: "main", id: entry.item.id)
                td = pluralize(entry.quantity, entry.item.unit)
        - else
          p No waste today.
  