config/routes.rb
Rails.application.routes.draw do
  resources :employees
  devise_for :admins

  root "pages#home"
  get "admin", to: "pages#admin_panel", as: "admin_panel"
  get "about", to: "pages#about", as: "about"

  resources :items
  get "search", to: "items#search"

  get  "items/:id/update", to: "entries#new", as: "new_entry"
  post "items/:id/update", to: "entries#create"
  get  "update", to: "entries#index", as: "entries"
  post "update", to: "entries#update", as: "update_entries"

  get  "items/:id/waste", to: "wastes#new", as: "new_waste"
  post "items/:id/waste", to: "wastes#create"
  get  "waste", to: "wastes#index", as: "wastes"
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :entries
  has_many :wastes
  before_create :default_entry

  validates :name, :unit, :category, :value, presence: true
  validates :name, uniqueness: true
  validates :threshold, numericality: { only_integer: true,
                                        greater_than_or_equal_to: 0 }
  validates :value, numericality: { greater_than_or_equal_to: 0 }

  private

  def default_entry
    entries.build(in_stock: 0, on_order: 0, note: nil, pin: 0000).save
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[edit update show destroy]

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      flash[:success] = 'Item created.'
      redirect_to root_path
    else
      flash.now[:danger] = 'Item not created.'
      render :new
    end
  end

  def edit
  end

  def update
    if @item.update_attributes(item_params)
      flash.now[:success] = 'Item updated.'
      redirect_to root_path
    else
      flash.now[:danger] = 'Item not updated.'
      render :edit
    end
  end

  def show
    if params[:period]
      @period = params[:period].downcase.to_sym
    else
      @period = :week
    end

    @entries = @item.entries.order(created_at: :desc)

    @stock_data = helpers.chart_avg(@item.entries, @period, :in_stock)
    @order_data = helpers.chart_avg(@item.entries, @period, :on_order)
    @waste_data = helpers.chart_avg(@item.wastes, @period, :quantity)
  end

  def index
    @items = Item.all.order(:name)
  end

  def destroy
    @item.destroy
    flash[:success] = 'Item deleted.'
    redirect_to items_path
  end

  def search
    @items = Item.where('name LIKE ?', "%#{params[:item_name]}%")
    if @items.count == 1
      redirect_to @items.first
    elsif @items.none?
      flash[:info] = 'No items found.'
      redirect_to root_path
    else
      render :index
    end
  end

  private

  def set_item
    unless (@item = Item.find_by(id: params[:id]))
      flash[:warning] = 'Item not found.'
      redirect_to items_path
    end
  end

  def item_params
    params.require(:item).permit(:name, :unit, :category, :threshold, :value)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.slim
- if @item.errors.any?
  .notification
    - @item.errors.full_messages.each do |message|
      ul
        li #{message}.

.field
  = form_for @item do |f|
    label.label Name
    .field
      .control
        = f.text_field :name, placeholder: "Cookie Dough", class: "input"

    label.label Unit
    .field    
      .control
        = f.text_field :unit, placeholder: "Tub", class: "input"
      p.help Singular unit to keep track of (ex. bag, box, tub)

    label.label Category
    .field
      .control
        = f.select :category, %w[Prepared Ingredients Supplies], class: "input"

    label.label Low-Stock Threshold
    .field
      .control
        = f.text_field :threshold, placeholder: "5", class: "input"
      p.help Number of units at which a low-stock alert is sent

    label.label Unit Value
    .field
      .control
        = f.text_field :name, placeholder: "Flour", class: "input"
      p.help Cost per unit, used in wastage

    .field
      .control
        = f.submit nil, class: "button is-success"

app/views/items/_item.html.slim
tr
  - if current_page?(controller: "entries")
    = form_for item do |f|
      td = item.name
      td = f.number_field :in_stock, value: item.in_stock
      td = item.unit
      td = f.number_field :on_order, value: item.on_order
      td = item.threshold
      td = item.value
      td #{time_ago_in_words(item.updated_at)} ago

  - else
    td = link_to item.name, item_path(anchor: "main", id: item.id)
    td = pluralize(item.in_stock, item.unit)
    td = item.on_order
    td = item.threshold
    td = item.value
    td #{time_ago_in_words(item.updated_at)} ago

  - if admin_signed_in?
    td = link_to "Edit", edit_item_path(item.id), class: "button is-small is-info"
    td = link_to "Delete", item, class: "button is-small is-danger", data: { confirm: "Are you sure?" }, method: :delete

app/views/items/edit.html.slim
= provide :title, 'Update Item'

h1.title Update Item Properties

= render 'form'

app/views/items/index.html.slim
= provide :title, "Inventory"

h1.title Inventory

table.table.is-striped.is-fullwidth
  .thead
    th Item
    th Stock
    th Order
    th Alert
    th Value
    th Updated
    - if admin_signed_in?
      th
      th
  .tbody
    = render @items 

app/views/items/new.html.slim
= provide :title, "New Item"

h1.title New Item

= render "form"

app/views/items/show.html.slim
= provide :title, @item.name

.columns
  .column
    == render "shared/item_box"
    == render "shared/item_history"
  .column
    == render "shared/item_chart"