config/routes.rb
Rails.application.routes.draw do
  resources :employees
  devise_for :admins

  root "pages#home"
  get "admin", to: "pages#admin_panel", as: "admin_panel"
  get "about", to: "pages#about", as: "about"

  resources :items
  get "search", to: "items#search"

  get  "items/:id/update", to: "entries#new", as: "new_entry"
  post "items/:id/update", to: "entries#create"
  get  "update", to: "entries#index", as: "entries"
  post "update", to: "entries#update", as: "update_entries"

  get  "items/:id/waste", to: "wastes#new", as: "new_waste"
  post "items/:id/waste", to: "wastes#create"
  get  "waste", to: "wastes#index", as: "wastes"
end

app/views/layouts/_footer.html.slim
footer.footer
  .level.is-mobile
    .level-left
      - if admin_signed_in?
          = link_to "Admin Panel", admin_panel_path, class: "level-item"
          = link_to "Log Out", destroy_admin_session_path, class: "level-item"
      - else  
        = link_to "Admin Login", new_admin_session_path, class: "level-item"
    .level-right
      = link_to "About", about_path, class: "level-item"
      = mail_to "brxck@protonmail.com", "Contact", class: "level-item"

app/views/layouts/_navbar.html.slim
nav.navbar.has-shadow.is-transparent role="navigation"
  .navbar-brand
    a.navbar-item href="#{root_path}"
      = image_tag "logo.png"
    button.button.navbar-burger.is-white data-target="nav-menu"
      span
      span
      span

  .navbar-menu#nav-menu
    .navbar-start
      .navbar-item.has-dropdown.is-hoverable
        .navbar-link Inventory
        .navbar-dropdown
            = link_to "Update", entries_path(anchor: "main"), class: "navbar-item"
            = link_to "View", items_path(anchor: "main"), class: "navbar-item"
            = link_to "Low Stock", "#", class: "navbar-item"

      .navbar-item.has-dropdown.is-hoverable
        .navbar-link Waste
        .navbar-dropdown
          = link_to "Log", new_waste_path(anchor: "main", id: 1), class: "navbar-item"
          = link_to "View", wastes_path(anchor: "main"), class: "navbar-item"

    .navbar-end
      .navbar-item
        = form_tag "/search", method: :get
        .field.has-addons
          .control
            button.button type="submit"
              span.icon.is-small
                = fa_icon "search"
          .control
            = text_field_tag :item_name, nil, placeholder: "Search items", class: "input"

javascript:
  document.addEventListener('DOMContentLoaded', function () {

    // Get all "navbar-burger" elements
    var $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

    // Check if there are any navbar burgers
    if ($navbarBurgers.length > 0) {

      // Add a click event on each of them
      $navbarBurgers.forEach(function ($el) {
        $el.addEventListener('click', function () {

          // Get the target from the "data-target" attribute
          var target = $el.dataset.target;
          var $target = document.getElementById(target);

          // Toggle the class on both the "navbar-burger" and the "navbar-menu"
          $el.classList.toggle('is-active');
          $target.classList.toggle('is-active');

        });
      });
    }

  });
                

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = "#{yield(:title)} | CookieCounter"
    = csrf_meta_tags
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload"
    = javascript_include_tag "application", "data-turbolinks-track": "reload"
    meta name="viewport" content="width=device-width" initial-scale=1

  body
    == render "layouts/navbar"

    - if current_page?("/about")
      == yield

    - else
      section.section#main
        div.container

          - flash.each do |type, message|
            div class="notification is-#{type}" #{message}

          == yield

    == render "layouts/footer"